### ISSUE TITLE
Event kütüphanesi için test yazılacak

### ISSUE THREAD

**Issue by SelimAbidin** [eyupinan/eventemt#1]
Mocha ile async test nasıl yazılır öğrenmen gerekecek. 

Yazılacak testler

- [x] Event objesi oluşturulacak ve emit ile callback çağırılıp çağırılmadığı test edilecek.
- [x] Event Objesine birden fazla fonksiyon eklenip, bir emit ile hepsinin tetiklenmesi test edilecek.
- [x] Event ile parametre gönderilip gönderilmediği test edilecek.
- [x] Event objesinden eventlar silinmesi test edilecek.
- [x] on, once test edilecek

Yapılanlar işaret lenip, issue güncellenecek

**Comment by eyupinan** [comment]
testler tamamlanmıştır . 'Emit' fonksiyonu asenkron olarak çalışmaktadır. Fakat 'on' fonksiyonu ile verilmiş olan fonksiyon 'emit' fonksiyonu ile çağırıldığında  çağırılan fonksiyon eğer beklenenden uzun sürüyor ise (Örneğin verilen fonksiyonun setTimeOut içermesi) test hata veriyor

**Comment by SelimAbidin** [comment]
[Örnekteki](https://mochajs.org/#asynchronous-code) kodu inceleyip, kendi koduna uygulayabilirsin.
Uygulama sonrası bana bildirim atarsan kontrol edip, issue'yu kapatabilirim.
