### ISSUE TITLE
Eslint Kurulumu

### ISSUE THREAD

**Issue by SelimAbidin** [eyupinan/eventemt#2]
Eslint kodları oluşturulan yada belli standartlar dahilinde kodları düzenlemeye yaran bir kütüphanedir.

### Yapılması gerekenler 

- [x] Eslint kurulumu
- [x] Eslint kurulumunda Standart kurulumun seçilmesi.
- [x] Seçilmiş olan Standart şablonda boşluğun 4'e çıkartılması.
- [x] "npm run lint" denildiğinde lint denetimi yapılması
- [x] linkt denetiminin travis CI işle beraber çalışması.

**Comment by eyupinan** [comment]
Tamamlandı. Eğer bir problem var ise yeni issue açarsınız. Issue'yi kapatıyorum
