### ISSUE TITLE
Core Object "remove" should work'

### ISSUE THREAD

**Issue by SelimAbidin** [eyupinan/eventemt#4]
class methodu remove için 2 tane string bekliyor.
remove(string, function) şeklinde olması gerekiyor.
Bu düzeldiğinde, test de tamamen çalışacak.

https://github.com/eyupinan/eventemt/blob/d185389ff0aa4ed177c7a70d76dc1038e36aeb36/tests/CoreObject.test.js#L55

**Comment by eyupinan** [comment]
Çalışmamasının sebebi 'remove' fonksiyonuna fonksiyonun ismini vermeniz gerekmesidir string olarak fonksiyon ismi alır .

**Comment by SelimAbidin** [comment]
fonksiyonun adı string olarak verilmemeli. fonksiyonun kendisi verilmeli.

`obje.on('eventType',   buraya neden fonksiyon ismi yazmadın?   )`

**Comment by eyupinan** [comment]
düzeltildi
